#!/usr/bin/env python3
"""
Generate GOTCHAS.md from structured gotchas.yaml data.
Always edit data/gotchas.yaml, not GOTCHAS.md directly.
"""

import yaml
import sys
from pathlib import Path
from typing import List, Dict

ROOT = Path(__file__).parent.parent
INPUT_YAML = ROOT / "data" / "gotchas.yaml"
OUTPUT_MD = ROOT / "GOTCHAS.md"

HEADER = """# C++ AI GOTCHAS

These are common patterns AI gets wrong when writing or reviewing C++ code.
**DO NOT EDIT THIS FILE DIRECTLY**
Edit data/gotchas.yaml instead, then run scripts/build_gotchas_md.py to regenerate.

---

## Categories
- [Ownership & Lifetime](#ownership--lifetime)
- [Concurrency & Thread Safety](#concurrency--thread-safety)
- [Error Handling](#error-handling)
- [Performance & Optimization](#performance--optimization)
- [Class & Object Model](#class--object-model)
- [Modernization & Best Practices](#modernization--best-practices)

---
"""

def load_gotchas() -> List[Dict]:
    """Load gotchas from YAML file."""
    try:
        with open(INPUT_YAML, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"❌ Failed to load gotchas.yaml: {e}", file=sys.stderr)
        return []

def group_by_category(gotchas: List[Dict]) -> Dict[str, List[Dict]]:
    """Group gotchas by category."""
    groups = {}
    for g in gotchas:
        cat = g["category"]
        if cat not in groups:
            groups[cat] = []
        groups[cat].append(g)
    
    # Sort groups by common priority
    priority_order = [
        "ownership", 
        "lifetime",
        "concurrency", 
        "error handling", 
        "performance",
        "classes",
        "modernization"
    ]
    
    # Create display names mapping
    display_names = {
        "ownership": "Ownership & Lifetime",
        "lifetime": "Ownership & Lifetime",
        "concurrency": "Concurrency & Thread Safety",
        "error handling": "Error Handling",
        "performance": "Performance & Optimization",
        "classes": "Class & Object Model",
        "modernization": "Modernization & Best Practices"
    }
    
    # Reorder groups according to priority
    ordered_groups = {}
    for prio in priority_order:
        if prio in groups:
            display_name = display_names[prio]
            if display_name not in ordered_groups:
                ordered_groups[display_name] = []
            ordered_groups[display_name].extend(groups[prio])
    
    # Add any remaining groups not in priority list
    for cat, items in groups.items():
        if cat not in priority_order:
            ordered_groups[cat] = items
    
    return ordered_groups

def generate_markdown(groups: Dict[str, List[Dict]]) -> str:
    """Generate markdown from grouped gotchas."""
    md = HEADER
    
    for category_name, items in groups.items():
        # Add category anchor
        anchor = category_name.lower().replace(" & ", "-").replace(" ", "-")
        md += f"\n## {category_name}\n"
        md += f'<a id="{anchor}"></a>\n\n'
        
        for g in items:
            md += f"### ❌ {g['title']}\n\n"
            md += f"**Symptom:**\n```cpp\n{g['symptom']}\n```\n\n"
            md += f"**Risk:** {g['risk']}\n\n"
            md += f"**Recommended Action:** {g['recommended_action']}\n\n"
            if g.get("tags"):
                md += f"*Tags: {', '.join(g['tags'])}*\n\n"
            md += "---\n\n"
    
    # Add footer
    md += f"""
## 📝 Adding New Gotchas

1. Edit `data/gotchas.yaml`
2. Add your gotcha following the existing format:
```yaml
- id: unique_id_001
  category: ownership/lifetime/concurrency/error handling/performance/classes/modernization
  title: Short descriptive title
  symptom: "Short code example showing the problem"
  risk: What goes wrong?
  recommended_action: How to fix it?
  tags: ["tag1", "tag2"]
  source: Where did this come from? (Real AI failure case, Core Guidelines, etc.)
```
3. Run `python3 scripts/build_gotchas_md.py` to regenerate this file
4. Commit both files

## 📊 Stats
Total gotchas: {sum(len(items) for items in groups.values())}
Last updated: $(date -I)
"""
    return md

def main() -> int:
    """Main function."""
    gotchas = load_gotchas()
    if not gotchas:
        print("❌ No gotchas loaded", file=sys.stderr)
        return 1
    
    groups = group_by_category(gotchas)
    markdown = generate_markdown(groups)
    
    with open(OUTPUT_MD, 'w', encoding='utf-8') as f:
        f.write(markdown)
    
    print(f"✅ Generated {OUTPUT_MD} with {len(gotchas)} gotchas in {len(groups)} categories")
    return 0

if __name__ == "__main__":
    sys.exit(main())
